sudo: required
services:
  - docker

before_install:
  - docker build -t silvmike/fakedns-server -f ./fakedns-server/Dockerfile ./fakedns-server

after_success:
  - echo "$HUB_PWD" | docker login -u "$HUB_USER" --password-stdin
  - docker push silvmike/fakedns-server