#!/bin/bash

if [ $JAVA_HOME ]
then
   RUN_JAVA=$JAVA_HOME/bin/java
else
   RUN_JAVA=`which java 2>/dev/null`
fi

if [ -z $RUN_JAVA ]
then
    echo "JAVA could not be found in your system."
    echo "please install Java 1.6 or higher!!!"
    exit 1
fi

FAKEDNS_HOME=/var/fakedns-server
PID_FILE=/var/tmp/fakedns-server.pid
FAKEDNS_HOST="0.0.0.0"
FAKEDNS_REGISTER_PORT=8099
FAKEDNS_ARGS="-m --pidfile $PID_FILE --exec $RUN_JAVA -- -jar $FAKEDNS_HOME/fakedns-server-1.0-SNAPSHOT.jar $FAKEDNS_HOST $FAKEDNS_REGISTER_PORT"

isAlive() {
  start-stop-daemon -S -t $FAKEDNS_ARGS > /dev/null
  if [ "$?" = "0" ]; then 
    return 1
  else 
    return 0
  fi
}

i="0"
startService() {
 if isAlive; then
  echo "FakeDNS service is already running!"
  return 0
 else
  start-stop-daemon -S -v -b $FAKEDNS_ARGS
  while [ $i -lt 3 ] 
  do
   echo "..."
   sleep 1;
   if isAlive; then
    i="3";
   else
    i=$[ $i + 1 ]
   fi
  done
  if isAlive; then
   echo "[ OK ]"
   return 1
  else 
   echo "[ Fail ]"
   return 0
  fi
 fi
}

stopService() {
 if isAlive; then
  start-stop-daemon -K $FAKEDNS_ARGS
  while [ $i -lt 3 ] 
  do
   echo "..."
   sleep 1;
   if isAlive; then
    i=$[ $i + 1 ]
   else 
    i="3";
   fi
  done
  if isAlive; then
   echo "[ Failed to stop ]"
  else 
   echo "[ Stopped ]"
  fi
  return 1
 else
  echo "FakeDNS service is not running!"
  return 0
 fi
}

printStatus() {
 if isAlive; then
  echo "* FakeDNS is running. PID: $(cat $PID_FILE)"
  return 1
 else
  echo "* FakeDNS service is not running."
  return 0
 fi
}

case $1 in
start)
 startService
;;
stop) 
 stopService
;;
restart)
 stopService
 startService
;;
status)
 printStatus
;;
*)
 echo "Usage: $0 {start|stop|restart|status}" >&2
 exit 1
esac 

exit 0

